[package]
authors = ["Alex Ryapolov <ryapolov@pm.me>"]
edition = "2018"
name = "journal"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
